name: rex
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  ansicolor: ^2.0.1
  args: ^2.3.2
  collection: ^1.17.0
  io: ^1.0.5
  path: ^1.9.0
  pub_api_client: ^3.2.0
  pubspec_parse: ^1.5.0

dev_dependencies:
  rexios_lints: ^17.0.3

executables:
  rex: rex
